import Nav from "./components/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";

export const revalidate = 3600;

export const metadata: Metadata = {
  title: "Next.js Image Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <Providers>
          <main className="max-w-6xl mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
